# Generated by Django 4.1.2 on 2022-11-20 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='update',
            new_name='update_at',
        ),
    ]
