# Generated by Django 4.1.2 on 2022-12-16 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.IntegerField(blank=True),
        ),
    ]
