# Generated by Django 4.1.2 on 2022-12-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default=0, unique=False),
            preserve_default=False,
        ),
    ]
